### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by joy1314** [basvandenberg/spice#2]
when I have installed this and I typed "from spice import featext"
It shows the error like this ,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spice/featext.py", line 14, in <module>
    from spice import featmat
  File "/usr/local/lib/python2.7/dist-packages/spice/featmat.py", line 21, in <module>
    sys.path.insert(1, os.environ['SKL'])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SKL'

Do you know why?How to fix it?

**Comment by basvandenberg** [comment]
Hi @joy1314,

Thanks for posting this issue. I updated the software, and with the latest version you should not get this error anymore.

To install spice, make sure to have the following required software installed (the commands below are for a debian-based linux system):
```
sudo apt install python-tk
pip install --user numpy scipy matplotlib sklearn prody
```
To be sure, remove your current biopy and spice installations:
```
cd /usr/local/lib/python2.7/dist-packages
sudo rm -rf spice
sudo rm SPiCE-*
sudo rm -rf biopy
sudo rm biopy-*
cd /usr/local/bin
sudo rm classification classify featext job_runner
```
And then install the latest biopy and spice:
```
cd ~/Downloads
wget https://github.com/basvandenberg/biopy/archive/develop.zip
unzip develop.zip
cd biopy-develop
sudo python setup.py install
cd ~/Downloads
wget https://github.com/basvandenberg/spice/archive/master.zip
unzip master.zip
cd spice-master
sudo python setup.py install
cd ~/Downloads
rm develop.zip
rm master.zip
rm -rf biopy-develop
rm -rf spice-master
```

I hope this works for you. This software is developed some time ago and not maintained since. Please let me know if something is not working properly or if you need more help.

**Comment by joy1314** [comment]
Thanks ,it works .But I have another question. I can not open http://helix.ewi.tudelft.nl/spice .what is the matter?How to fix it ??
Looking forward to your reply
Thank you very much.

**Comment by joy1314** [comment]
@basvandenberg Now I have another problem
When I type`classification` and `classify`on the command line .I shows the error like this
`raceback (most recent call last):
  File "/usr/local/bin/classification", line 16, in <module>
    sys.path.insert(1, os.environ['SKL'])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SKL'
`

`Traceback (most recent call last):
  File "/usr/local/bin/classify", line 5, in <module>
    from spice.classify import classify
  File "/usr/local/lib/python2.7/dist-packages/spice/classify.py", line 9, in <module>
    sys.path.insert(1, os.environ['SKL'])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SKL'
`
How to fix them?
Thank you very much

**Comment by joy1314** [comment]
thank you very much @basvandenberg
